#!/bin/sh
cat > /bin/emq-TE1-update <<- "EOF"
#!/bin/bash
sudo rm -r /opt/*
sudo rm /bin/MENU
sudo rm /bin/menu*
sudo bash -c "$(wget -O - https://github.com/hp3icc/emq-TE1ws/raw/main/emq-TE1ws.sh)"
EOF
chmod +x /bin/emq-TE1-update
/bin/emq-TE1-update
